server:
  port: 9001

msg:
  name: Shubhan
  val: JAVAKING
  list: one,two,three
  map: "{name:'raja',sub:'java'}"
db:
   connection: some connection
   port: 1234
   host: local


spring:
  profiles:
    active: test
#  cloud:
#    config:
#      uri: http://localhost:8888
  application:
    name: spring-boot-config
#actuaror properties
#management.endpoints.web.exposure.include:"*"